### ISSUE TITLE
Problem with setting Baudrate 19200 (TypeError: "baudRate" must be a number: 19200)

### ISSUE THREAD

**Issue by V3NK47** [yaacov/node-modbus-ws#12]
I'm using `modbus-ws -s COM3 -b 19200 -P 9000` to start the server. The error is thrown TypeError: 

----------------------------------------------------
Modbus-WS server 2.2.0
    Setup serial port: COM3 19200
C:\Users\VS\AppData\Roaming\npm\node_modules\modbus-ws\node_modules\serialport\lib\serialport.js:125
    throw new TypeError(`"baudRate" must be a number: ${settings.baudRate}`);
    ^

TypeError: "baudRate" must be a number: 19200
    at new SerialPort (C:\Users\VS\AppData\Roaming\npm\node_modules\modbus-ws\node_modules\serialport\lib\serialport.js:125:11)
    at Object.start (C:\Users\VS\AppData\Roaming\npm\node_modules\modbus-ws\server.js:425:22)
    at Object.<anonymous> (C:\Users\VS\AppData\Roaming\npm\node_modules\modbus-ws\bin\modbus-ws.js:53:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)

**Note:** I tried the same in linux. Same error.

**Comment by yaacov** [comment]
can you try changing line 425 [1] :
``` js
serialPort = new SerialPort(port, {baudRate: parseInt(baud)}, false);
```
insead of:
``` js
serialPort = new SerialPort(port, {baudRate: baud}, false);
```

[1] https://github.com/yaacov/node-modbus-ws/blob/b6c2311b914a8abb6aeafb2f56eb6fcfe1ad7ada/server.js#L425

**Comment by cpfarher** [comment]
@V3NK47 I think this is solved, please close if it's ok. Thank You
