### ISSUE TITLE
throw new TypeError(`"baudRate" must be a number: ${settings.baudRate}`)

### ISSUE THREAD

**Issue by oharkins** [yaacov/node-modbus-ws#37]
after installing this via the npm install global and trying to set the baud rate I get this error. 
I pulled the git and built on the device and ran directly and that works but using global does not. 

`modbus-ws -s /dev/ttyUSB0 -b 115200

----------------------------------------------------
Modbus-WS server 2.2.0
    Setup serial port: /dev/ttyUSB0 115200
/usr/local/lib/node_modules/modbus-ws/node_modules/@serialport/stream/lib/index.js:124
    throw new TypeError(`"baudRate" must be a number: ${settings.baudRate}`)
    ^

TypeError: "baudRate" must be a number: 115200
    at new SerialPort (/usr/local/lib/node_modules/modbus-ws/node_modules/@serialport/stream/lib/index.js:124:11)
    at Object.start (/usr/local/lib/node_modules/modbus-ws/server.js:425:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/modbus-ws/bin/modbus-ws.js:53:8)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47`

**Comment by yaacov** [comment]
thank you for the issue, can you make a pull request converting the boud string to number ?

**Comment by oharkins** [comment]
This looks to have been fixed in 0a78cf4fb497852b17a43290bbe3126c235484c0 fix bug issue #12
Looks like the package has not been pushed to [ npm](https://www.npmjs.com/) in 5 years is there a way we can get that pushed over?

**Comment by yaacov** [comment]
https://www.npmjs.com/package/modbus-ws/v/2.2.1 :tada:

**Comment by oharkins** [comment]
Thanks!
